### ISSUE TITLE
Slow download of 13F filings

### ISSUE THREAD

**Issue by HedgeShot** [jadchaar/sec-edgar-downloader#20]
Hi,

I used your tool 3 months ago with the method `get_13f_filing_for_cik` to download around 140 13Fs. It took around around 5 minutes. I tried again to download 13F for the same list of CIKs after updating your package. I am now using the method `get_13f_hr_filings`. It took much more time than last time (around 1 hour). Is it to be expected?

Thanks!

**Comment by jadchaar** [comment]
Hey @HedgeShot, thanks for reaching out! I refactored the package and unified the methods for CIK and tickers into one since the API got cluttered and duplicated otherwise.

I am guessing you were using version `<2.0`. In version `1.x.x`, I used streams to download the filings, but I since changed to using conventional requests after doing some research and reading (the filings did not seem large enough to warrant the use of streams). That said, I find it quite odd that you see such a huge change in the download performance.

Would it be possible to provide me with a list of the CIKs you are downloading? Also, is it possible that you are getting a weaker signal or slower download speeds than last time?

I also wonder if SEC Edgar is rate-limiting your IP. These are all variables I would like to investigate. Let me know :). I am not opposed to re-visiting streams, but I'd like to get a full picture of the issue before moving forward.

**Comment by HedgeShot** [comment]
Hey,

Thanks for your answer. I don't think the issue as to do with the CIKs I am calling. The time it takes per CIK is fairly the same for each. Connection can't completely ruled out as I was on a 4G dongle but speed test done that day showed similar speed as the other wired connection I am usually using.

I don't do anything that requires speed regarding those 13F, so I am fine with the slower connection speed. I was just wondering if it was expected. I will try again on a wired connection and will let you know how it goes.

Thanks again

**Comment by jadchaar** [comment]
Thanks for the response @HedgeShot. This is not expected, so I'd like to look into it. If you could try this on your wired connection and report your findings, it would help a lot!

I have had bad luck with 4G dongles. A lot of the time, the carrier throttles you if you are making a lot of subsequent connections.

**Comment by jadchaar** [comment]
Hey @HedgeShot, is this still occurring for you?

**Comment by HedgeShot** [comment]
Hi, I haven’t tried again yet as I’m running the script each quarter only. I will have a look mid-November at the latest and will let you know

**Comment by jadchaar** [comment]
No problem :). I just though I'd follow up since it has been a while. No rush.

**Comment by jadchaar** [comment]
Hey @HedgeShot any updates on this? Today SEC Edgar has been very slow for me, so it is making me think that the slowness you encountered may be on the side of the SEC.

**Comment by HedgeShot** [comment]
Hey @jadchaar, last time I used it, it was much faster. I did it on another internet connection so i don't know yet if it is due to the connection speed or the SEC website.
