### ISSUE TITLE
Get all filings without specifying CIK or ticker

### ISSUE THREAD

**Issue by lamberpj** [jadchaar/sec-edgar-downloader#21]
Hi jadchaar,

I am transitioning from the R tool "Edgar" to your tool, using Google Collab to download directly to my Google Drive.

I was wondering if there is scope to use your tool to download all available content for, say, a specific year?  For example, I want to specify "2017" and then get all the 10-Ks filed in that year.

I know I can just find all the CIKs, and feed them in, but this means looking up all the new values each quarter and I wondered if there was a simpler way?

Also, is your tool capable of pulling 10-KSBs?

Thanks so much in advance!

Pete

**Comment by jadchaar** [comment]
Hi @lamberpj, thanks for using the tool :). Sadly, the functionality to bulk download all filings in a particular year is unavailable in the current version of the tool. This is definitely an interesting feature that I would like to investigate further in the future since it would require tapping additional data sources provided by the SEC.

The tool does not currently support 10-KSBs, but support for them can be easily added. Do you think you can provide me with an example of a company that may have 10-KSBs?

Thanks,
Jad

**Comment by lamberpj** [comment]
Hi Jad,

Thanks for the lightning fast response! I count 36,912 10KSB filings as of today, an example of which is:

CIK: 1411460
NAME: UBIQUITECH SOFTWARE CORP
Filing Date: 2008-11-26
Link: edgar/data/1411460/0001079974-08-000990.txt
Quarter:  4
Year: 2008

This would be greatly appreciated, thank-you so much!

**Comment by jadchaar** [comment]
Awesome, hopefully I will get some time over the next few days to add support for 10KSB filings :).

**Comment by jadchaar** [comment]
Hey @lamberpj, I just released v2.2.1 with support for form 10KSB :).

You can run `pip install -U sec-edgar-downloader` to upgrade it.

**Comment by jadchaar** [comment]
Hey @lamberpj, I am working on v3.0.0 of this package with support for specifying an `after_date` parameter. This will allow you to accomplish what you are requesting: you can specify `2019-01-01` as the `after_date` and `2019-12-31` as the `before_date` to get all filings of a particular type for a ticker in the year 2019. All you need to do is find a list of all tickers in the markets (you can compile a list of all tickers with OpenFIGI) and iterate through each one with a specified `after_date` and `before_date`.

Hopefully you will find v3.0.0 useful when I release it in the near future. I do not think I will be able to integrate the full functionality that you are requesting (getting all filings in a year for all tickers) because tickers are constantly being removed and added. Maintaining a reliable ticker database would be tough and would make the package size unwieldy. 

Stay tuned for v3.0.0 :). Closing this for now.
