### ISSUE TITLE
Add an option to pull statements after a specific date

### ISSUE THREAD

**Issue by pucek80** [jadchaar/sec-edgar-downloader#23]
Hi,

Thank you for your current work. I've been using the package to collect data. I was wondering if you would consider including an option to download statements posted after a specific date (currently there is only an option for before date)

Thanks,
Bart

**Comment by jadchaar** [comment]
Hey @pucek80, thanks for using the tool! The reason I currently only support "before_date" is because that is natively supported by the EDGAR system without the need for manual processing. That said, it is definitely possible to add an "after_date" field, but it will require extra processing of the [XML data](https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193&type=&dateb=&owner=exclude&start=0&count=40&output=atom). I will try to work on this when I get a free moment. If you'd like to submit a PR, go for it!

**Comment by pucek80** [comment]
I've never done one before. I assume I should go to Pull requests and then somehow add a new one?

**Comment by jadchaar** [comment]
Hey @pucek80, if you'd like to make the contribution, go for it, but do not feel obligated at all to do it :). I will get around to it at some point!

If you'd like to make the contribution, first start by forking this repository. Then, you can create a branch, make your changes, and go to the pull requests tab in Github to submit a PR with your new branch. More info on making contributions can be found here: https://opensource.guide/how-to-contribute/.

Let me know if you have any remaining questions or concerns. Happy coding!
