### ISSUE TITLE
Add flag to slow down requests to prevent rate limiting

### ISSUE THREAD

**Issue by jadchaar** [jadchaar/sec-edgar-downloader#24]
If too many requests are made over a short period of time, SEC EDGAR begins to rate limit and eventually block an IP, resulting in the following exception:

```shell
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.sec.gov', port=443): Max retries exceeded with url: /Archives/edgar/data/.../.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11b111790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))\
```

It would be nice to investigate a possible way to automatically limit the number of requests by potentially sleeping at certain intervals if a flag is set.

**Comment by Alex6614** [comment]
I'm getting a similar error too:

`HTTPSConnectionPool(host='www.sec.gov', port=443): Max retries exceeded with url: /cgi-bin/browse-edgar?action=getcompany&owner=exclude&start=0&count=100&CIK=FISV&type=10-K&dateb=20200120&output=atom (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))`

Not sure if this is due to my firewall, though.

**Comment by jadchaar** [comment]
@Alex6614 if filings were successfully downloaded to the specified folder, this must mean that your IP has been blacklisted, and adding the sleep command won't work until you get another IP. I would try and obtain another IP address (e.g. by re-connecting your wifi) and try again with the sleep commands included.

**Comment by mksamelson** [comment]
What do you mean "by re-connecting your wifi"?  If using a `dl.get()` statement in a loop there is no specification of the URL so I'm not clear what you mean.  Could you elaborate?  Thanks

**Comment by jadchaar** [comment]
Hey @mksamelson, sorry I should make that more clear. What I mean is that you need to establish a new IP address since the SEC temporarily blacklisted your current one for rate limiting purposes. So you simply need to disconnect your wifi on your machine and reconnect to it to establish a new IP address. This works because most computers obtain an IP address with a process called DHCP.

This is an example of what you should do to prevent rate limiting:

```python
import time

symbols = ["AAPL", "MSFT", "0000102909", "V", "FB"]
for s in symbols:
    for filing_type in dl.supported_filings:
        dl.get(filing_type, s, 10)
        time.sleep(5)
```

5 seconds may be too little or too much--it will take some experimentation on your part, but the idea stands. We are trying to not send too many network requests at once to the SEC server by sleeping between each bulk download request.

**Comment by mksamelson** [comment]
Thanks for your reply.

So I put in sleep for 25 seconds between `dl.get` calls in my loop.  My script also does some intensive parsing of the files so in my case it is probably 2 to 3 minutes between bulk pulls.   So it looks like I'm already following your guidance.

Still, I'm finding after about 40 to 50 pulls sec.edgar blocks me and kills my script.  It's strange because it's not like I'm doing excessive pulling or tying up their servers.   Trying a work around with some error handling now.  Will come back with the results.

**Comment by jadchaar** [comment]
You may still be blacklisted if the calls to `dl.get` involve a large number of filings (e.g. 100+), so splitting up the number of filings you download for each call to `dl.get` could also help prevent this.

For example: you could change a call like `dl.get("8-K", "AAPL", 300)` into 3 calls with 100 filings each.

**Comment by mksamelson** [comment]
That is probably what is happening in my case.

**Comment by mksamelson** [comment]
Fix:  Implement a delay in your `download_files' utility.  SEC Edgar only allows 10 tries per second before blocking.  Do a `time.sleep(.15) to be safe and there will be no block.  And it's one line of code.

**Comment by jadchaar** [comment]
@mksamelson thanks a ton for investigating this issue. If you would like to implement the change and submit a pull request, feel free to! Otherwise, I will make the change myself soon.

**Comment by jadchaar** [comment]
I just pushed v3.0.2 of the package with the added sleep statement to prevent rate limiting.
