### ISSUE TITLE
" f"'{filing_type}' filings are not supported" thrown on import

### ISSUE THREAD

**Issue by ctrlaltd** [jadchaar/sec-edgar-downloader#30]
Hey there! Very excited to use this tool, but I'm having a little problem starting out. I've only added the import and instantiation of the Downloader class, run my python file, and get this:

from sec_edgar_downloader import Downloader
  File "/home/cecelia/.local/lib/python3.5/site-packages/sec_edgar_downloader/Downloader.py", line 112
    f"'{filing_type}' filings are not supported. "

Any idea what the issue could be?

**Comment by jadchaar** [comment]
Hey @ctrlaltd, thanks for reaching out! I actually made this tool with Python 3.6+ in mind because I am using the Pathlib module extensively to make file path operations simpler and more maintainable. I tried back-porting it to Python 2.7 and Python 3.5, but doing so would have required an extensive refactor and reliance on a third party Pathlib package (outside of the standard library). Would it be possible to upgrade Python to Python 3.6+ and try again?

If you need help, let me know!

**Comment by ctrlaltd** [comment]
That did the trick! Thanks so much for the support!
