### ISSUE TITLE
Add a limiter to not request past the SEC's 10 requests per second limit

### ISSUE THREAD

**Issue by 3sticks** [jadchaar/sec-edgar-downloader#46]
I know we can just sleep(1) in a for loop when we run .get, but before I realized there was a limit, I actually had my IP address blocked. Luckily I can get around it, but others might not be so lucky. But, perhaps, ignorance comes at a cost, and maybe you don't have to do anything about it. I just thought I would bring it up. It's possible it wasn't even the 10 second limit, and they blocked me for just sheer volume (I have been hitting this thing for 4 straight days). Also, I didn't dig too deep into your library, and you may already have a limiter baked in. If so, I apologize for making you read this. 

This thing works BEAUTIFULLY, for what its worth. Thank you for this wonderful contribution to the community.

**Comment by jadchaar** [comment]
Hi @3sticks thanks for using this package and I appreciate the kind words. That is interesting that you encountered a rate limit because I implemented a 15ms sleep call in the download looping logic thanks to a suggestion in https://github.com/jadchaar/sec-edgar-downloader/issues/24. Basically, a user suggested that the SEC Edgar system requires less than 10 requests per second before it rate limits/blocks your IP, so I put a `time.sleep(.15)` call in the download loop: https://github.com/jadchaar/sec-edgar-downloader/blob/022c70e54b0e8b3359833d9942b4854f7eefe088/sec_edgar_downloader/_utils.py#L134

Did you encounter this block after 4 straight days of downloading? If so, it might just be due to sheer volume.

**Comment by 3sticks** [comment]
@jadchaar ah, I should have looked at the source code! It is very possible it was just due to sheer volume. I wasn't querying that many CIKs, but who knows. 

I should have trusted that you had it baked in. Everything works great. Sorry for falsely bringing this up!

**Comment by jadchaar** [comment]
No problem at all @3sticks, I am always open to improving this package! Please let me know if it occurs again. It would be great to gather some data on when the block/rate limit occurs and what queries were being made so we can get a sense of what is causing it. The SEC site is very unfriendly to scrapers, so the rate limits may have changed since I last took a look :).
