### ISSUE TITLE
404 on a filing halts the download

### ISSUE THREAD

**Issue by clifton** [jadchaar/sec-edgar-downloader#54]
```python
cik = '0000101778' # marathon petroleum
Downloader("dl").get("8-K", marathon['cik'], download_details=True, include_amends=True)

# => HTTPError: 404 Client Error: Not Found for url: https://www.sec.gov/Archives/edgar/data/0000101778/000095013201000132/0001.txt
```

perhaps the right thing would be to log the 404 and continue?

im happy to create a patch and send a pull request if that is OK

**Comment by jadchaar** [comment]
Hi @clifton, thanks for reporting this! This seems to be due to an issue with the EDGAR Search API on this 8-K entry: https://www.sec.gov/edgar/search/#/dateRange=custom&category=custom&entityName=0000101778&startdt=2001-02-26&enddt=2001-02-28&forms=8-K.

The Search API seems to return the following:

```json
{
        "_index": "edgar_file",
        "_type": "_doc",
        "_id": "0000950132-01-000132:0001.txt",
        "_score": null,
        "_source": {
          "ciks": [
            "0000101778"
          ],
          "period_ending": "2001-02-27",
          "root_form": "8-K",
          "file_num": [
            "001-05153"
          ],
          "display_names": [
            "USX CORP  (MRO)  (CIK 0000101778)"
          ],
          "xsl": null,
          "sequence": "1",
          "file_date": "2001-02-27",
          "biz_states": [
            "PA"
          ],
          "sics": [
            "2911"
          ],
          "form": "8-K",
          "adsh": "0000950132-01-000132",
          "film_num": [
            "1554923"
          ],
          "biz_locations": [
            "Pittsburgh, PA"
          ],
          "file_type": "8-K",
          "file_description": "FORM 8-K",
          "inc_states": [
            "DE"
          ],
          "items": [
            "5",
            "7"
          ]
        },
        "sort": [
          983232000000
        ]
      },
```

According to the HTML download page here https://www.sec.gov/Archives/edgar/data/0000101778/000095013201000132/0000950132-01-000132-index.html, the URL should really be https://www.sec.gov/Archives/edgar/data/101778/000095013201000132/0000950132-01-000132-0001.txt, but the search API gives us an incomplete `0001.txt` filename. I think the best solution is to simply pass as you stated (and maybe give a nice error message to the user) since it would be a bit clunky to fix this edge case. I will report this to the SEC Edgar team! I will also work on PRing a patch for this issue using your suggestion!

**Comment by jadchaar** [comment]
I just released v4.0.1 to fix this @clifton! Let me know if this fixes the issue :).

**Comment by clifton** [comment]
Fantastic! Thanks for the quick response

**Comment by jadchaar** [comment]
Got back a response from the SEC and I wanted to share the response for the record:

> It looks like the problem is that the extracted files from this 2001-02-27 filing has a different file name (e.g. 0000950132-01-000132-0001.txt) from what is displayed on screen (e.g. 0001.txt) and is found in the “Complete submission text file”
> ...
> Staff are looking at the issue, but may not be able to fix archival structural differences in filings. The Full Text search doesn’t index year 2000 and earlier filings for this reason.

So this is definitely an issue on the SEC side of things, but it seems isolated (hopefully) to filings before 2001!
