### ISSUE TITLE
10-Q for symbol "V" doesn't return Visa Inc.

### ISSUE THREAD

**Issue by weseemahmed** [jadchaar/sec-edgar-downloader#93]
Searching for symbol "V" for 10-Q forms returns other securities besides Visa Inc. depending on quarterly submission. 10-K appears to work fine.

**Comment by jadchaar** [comment]
Hey @weseemahmed! This is due to the package's underlying use of the [SEC full text search API](https://www.sec.gov/edgar/search/). The API is a bit lenient in it's query abilities, so I recommend getting around this bug by fetching filings using the CIK for Visa: `1403161`. You can find CIKs for tickers using this website: https://www.sec.gov/edgar/searchedgar/cik.htm

Let me know if any further issues arise :)!
